# Generated by Django 5.1.1 on 2024-09-27 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calidad_aire', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_hora', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='programaciondispositivo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='color',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='pin',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='programaciondispositivo',
            name='intensidad',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Metricas',
        ),
    ]
