# Generated by Django 5.1.1 on 2024-09-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medidashabitacion_remove_dispositivo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='longitud',
            field=models.FloatField(null=True),
        ),
    ]
