# Generated by Django 5.1.2 on 2024-10-08 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_casa_latitud_alter_casa_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='casa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.casa'),
        ),
    ]
