# Generated by Django 5.1.2 on 2024-10-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_casa_latitud_alter_casa_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='piso',
            field=models.PositiveIntegerField(),
        ),
    ]
