# Generated by Django 5.1.2 on 2024-10-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_habitacion_piso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='intensidad',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
