# Generated by Django 5.1.2 on 2024-10-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_casa_options_alter_dispositivo_intensidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='pin',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
