# Generated by Django 5.1.2 on 2024-10-09 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_dispositivo_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidashabitacion',
            name='habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.habitacion'),
        ),
    ]
