# Generated by Django 5.1.2 on 2024-11-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_habitacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='angulo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='velocidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='volumen',
            field=models.FloatField(default=0),
        ),
    ]
