# Generated by Django 5.1.2 on 2024-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_dispositivo_angulo_dispositivo_velocidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='angulo',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='pin',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='velocidad',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='volumen',
            field=models.FloatField(default=0, null=True),
        ),
    ]
